test_basic_logging (__main__.LogFormatterTest) ... ERROR

======================================================================
ERROR: test_basic_logging (__main__.LogFormatterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/log_test.py", line 108, in test_basic_logging
    self.assertEqual(self.get_output(), b"foo")
  File "test/log_test.py", line 104, in get_output
    raise Exception("output didn't match regex: %r" % line)
Exception: output didn't match regex: '[E 141015 17:42:16 log_test:107] foo'

----------------------------------------------------------------------
Ran 1 test in 0.011s

FAILED (errors=1)
